<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\ProfilIbuHamil;
use Illuminate\Support\Facades\Hash;

class IbuHamilSeeder extends Seeder
{
    public function run(): void
    {
        $ibuHamilData = [
            ['user' => ['nama_lengkap' => 'Fatimah Azzahra', 'email' => 'fatimah.azzahra@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567891'], 'profil' => ['tanggal_lahir' => '1995-03-15', 'usia' => 31, 'hpht' => '2025-01-20', 'hpl' => '2025-10-27', 'golongan_darah' => 'O', 'rhesus' => '+', 'berat_sebelum' => 58.5, 'tinggi_badan' => 158.0, 'alamat' => 'Jl. Mawar No. 5, Jakarta Pusat', 'riwayat_penyakit' => 'Diabetes Gestasional', 'riwayat_alergi' => 'Obat-obatan', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Siti Aminah', 'email' => 'siti.aminah@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567892'], 'profil' => ['tanggal_lahir' => '1998-07-22', 'usia' => 28, 'hpht' => '2025-02-10', 'hpl' => '2025-11-17', 'golongan_darah' => 'A', 'rhesus' => '+', 'berat_sebelum' => 52.0, 'tinggi_badan' => 162.0, 'alamat' => 'Jl. Kenanga No. 10, Bandung', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Dian Pertiwi', 'email' => 'dian.pertiwi@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567893'], 'profil' => ['tanggal_lahir' => '1993-11-01', 'usia' => 32, 'hpht' => '2024-12-05', 'hpl' => '2025-09-12', 'golongan_darah' => 'B', 'rhesus' => '-', 'berat_sebelum' => 65.0, 'tinggi_badan' => 160.0, 'alamat' => 'Jl. Melati No. 15, Surabaya', 'riwayat_penyakit' => 'Hipertensi Kronis', 'riwayat_alergi' => 'Seafood', 'kehamilan_ke' => 3, 'anak_hidup' => 2, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Rina Susilowati', 'email' => 'rina.susilowati@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567894'], 'profil' => ['tanggal_lahir' => '1997-05-18', 'usia' => 28, 'hpht' => '2025-03-01', 'hpl' => '2025-12-06', 'golongan_darah' => 'AB', 'rhesus' => '+', 'berat_sebelum' => 55.0, 'tinggi_badan' => 155.0, 'alamat' => 'Jl. Dahlia No. 22, Bekasi', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Polen', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Maya Kartika', 'email' => 'maya.kartika@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567895'], 'profil' => ['tanggal_lahir' => '1996-09-10', 'usia' => 29, 'hpht' => '2025-01-15', 'hpl' => '2025-10-22', 'golongan_darah' => 'O', 'rhesus' => '+', 'berat_sebelum' => 60.0, 'tinggi_badan' => 165.0, 'alamat' => 'Jl. Anggrek No. 8, Tangerang', 'riwayat_penyakit' => 'Anemia', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Lisa Andini', 'email' => 'lisa.andini@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567896'], 'profil' => ['tanggal_lahir' => '2000-02-28', 'usia' => 26, 'hpht' => '2025-02-20', 'hpl' => '2025-11-27', 'golongan_darah' => 'A', 'rhesus' => '+', 'berat_sebelum' => 50.0, 'tinggi_badan' => 160.0, 'alamat' => 'Jl. Seruni No. 3, Depok', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Kacang', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Nurul Hidayah', 'email' => 'nurul.hidayah@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567897'], 'profil' => ['tanggal_lahir' => '1994-08-14', 'usia' => 31, 'hpht' => '2024-11-25', 'hpl' => '2025-09-01', 'golongan_darah' => 'B', 'rhesus' => '+', 'berat_sebelum' => 62.0, 'tinggi_badan' => 158.0, 'alamat' => 'Jl. Kamal No. 17, Bogor', 'riwayat_penyakit' => 'Thyroid', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 1]],
            ['user' => ['nama_lengkap' => 'Ayu Wulandari', 'email' => 'ayu.wulandari@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567898'], 'profil' => ['tanggal_lahir' => '1999-12-05', 'usia' => 26, 'hpht' => '2025-03-10', 'hpl' => '2025-12-15', 'golongan_darah' => 'O', 'rhesus' => '-', 'berat_sebelum' => 54.0, 'tinggi_badan' => 163.0, 'alamat' => 'Jl. Flamboyan No. 12, Jakarta Selatan', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Susu', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Dewi Lestari', 'email' => 'dewi.lestari@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567899'], 'profil' => ['tanggal_lahir' => '1992-06-20', 'usia' => 33, 'hpht' => '2024-12-15', 'hpl' => '2025-09-21', 'golongan_darah' => 'A', 'rhesus' => '+', 'berat_sebelum' => 68.0, 'tinggi_badan' => 155.0, 'alamat' => 'Jl. Mangga No. 25, Jakarta Barat', 'riwayat_penyakit' => 'Diabetes Tipe 2', 'riwayat_alergi' => 'Obat keras', 'kehamilan_ke' => 4, 'anak_hidup' => 3, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Sari Rahmawati', 'email' => 'sari.rahmawati@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567800'], 'profil' => ['tanggal_lahir' => '1997-01-30', 'usia' => 28, 'hpht' => '2025-02-05', 'hpl' => '2025-11-12', 'golongan_darah' => 'AB', 'rhesus' => '+', 'berat_sebelum' => 56.0, 'tinggi_badan' => 161.0, 'alamat' => 'Jl. Jeruk No. 9, Bandung', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Putri Octavia', 'email' => 'putri.octavia@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567801'], 'profil' => ['tanggal_lahir' => '1995-04-12', 'usia' => 30, 'hpht' => '2025-01-10', 'hpl' => '2025-10-17', 'golongan_darah' => 'B', 'rhesus' => '+', 'berat_sebelum' => 59.0, 'tinggi_badan' => 167.0, 'alamat' => 'Jl. Apel No. 18, Surabaya', 'riwayat_penyakit' => 'Asma', 'riwayat_alergi' => 'Debu', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Indah Susanti', 'email' => 'indah.susanti@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567802'], 'profil' => ['tanggal_lahir' => '1998-10-25', 'usia' => 27, 'hpht' => '2025-03-05', 'hpl' => '2025-12-10', 'golongan_darah' => 'O', 'rhesus' => '+', 'berat_sebelum' => 53.0, 'tinggi_badan' => 159.0, 'alamat' => 'Jl. Pisang No. 6, Bekasi', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Telur', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Ratna Sari', 'email' => 'ratna.sari@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567803'], 'profil' => ['tanggal_lahir' => '1994-03-08', 'usia' => 31, 'hpht' => '2024-12-20', 'hpl' => '2025-09-26', 'golongan_darah' => 'A', 'rhesus' => '-', 'berat_sebelum' => 64.0, 'tinggi_badan' => 156.0, 'alamat' => 'Jl. Jambu No. 14, Jakarta Utara', 'riwayat_penyakit' => 'Hipertensi', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 3, 'anak_hidup' => 2, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Hana Fatharani', 'email' => 'hana.fatharani@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567804'], 'profil' => ['tanggal_lahir' => '2001-07-15', 'usia' => 24, 'hpht' => '2025-02-25', 'hpl' => '2025-12-02', 'golongan_darah' => 'AB', 'rhesus' => '+', 'berat_sebelum' => 48.0, 'tinggi_badan' => 162.0, 'alamat' => 'Jl. Nanas No. 7, Depok', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Ika Febriyanti', 'email' => 'ika.febriyanti@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567805'], 'profil' => ['tanggal_lahir' => '1996-11-22', 'usia' => 29, 'hpht' => '2025-01-25', 'hpl' => '2025-11-01', 'golongan_darah' => 'B', 'rhesus' => '+', 'berat_sebelum' => 57.0, 'tinggi_badan' => 160.0, 'alamat' => 'Jl. Belimbing No. 11, Tangerang', 'riwayat_penyakit' => 'Anemia', 'riwayat_alergi' => 'Ikan', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Wati', 'email' => 'wati@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567806'], 'profil' => ['tanggal_lahir' => '1993-09-30', 'usia' => 32, 'hpht' => '2024-11-15', 'hpl' => '2025-08-22', 'golongan_darah' => 'O', 'rhesus' => '+', 'berat_sebelum' => 66.0, 'tinggi_badan' => 154.0, 'alamat' => 'Jl. Sawo No. 20, Bogor', 'riwayat_penyakit' => 'Jantung', 'riwayat_alergi' => 'Obat', 'kehamilan_ke' => 3, 'anak_hidup' => 2, 'keguguran' => 1]],
            ['user' => ['nama_lengkap' => 'Yuni Astuti', 'email' => 'yuni.astuti@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567807'], 'profil' => ['tanggal_lahir' => '1997-06-18', 'usia' => 28, 'hpht' => '2025-02-15', 'hpl' => '2025-11-22', 'golongan_darah' => 'A', 'rhesus' => '+', 'berat_sebelum' => 55.0, 'tinggi_badan' => 164.0, 'alamat' => 'Jl. Pepaya No. 5, Jakarta Timur', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Tika Puspita', 'email' => 'tika.puspita@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567808'], 'profil' => ['tanggal_lahir' => '1995-12-01', 'usia' => 30, 'hpht' => '2025-01-05', 'hpl' => '2025-10-12', 'golongan_darah' => 'AB', 'rhesus' => '-', 'berat_sebelum' => 61.0, 'tinggi_badan' => 159.0, 'alamat' => 'Jl. Dukuh No. 16, Bandung', 'riwayat_penyakit' => 'Thyroid', 'riwayat_alergi' => 'Kaca', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Nisa Khoirunnisa', 'email' => 'nisa.khoirunnisa@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567809'], 'profil' => ['tanggal_lahir' => '1999-05-14', 'usia' => 26, 'hpht' => '2025-03-15', 'hpl' => '2025-12-20', 'golongan_darah' => 'B', 'rhesus' => '+', 'berat_sebelum' => 51.0, 'tinggi_badan' => 161.0, 'alamat' => 'Jl. Melon No. 8, Bekasi', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Fitriani', 'email' => 'fitriani@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567810'], 'profil' => ['tanggal_lahir' => '1994-02-20', 'usia' => 31, 'hpht' => '2024-12-10', 'hpl' => '2025-09-16', 'golongan_darah' => 'O', 'rhesus' => '+', 'berat_sebelum' => 63.0, 'tinggi_badan' => 157.0, 'alamat' => 'Jl. Kersen No. 13, Surabaya', 'riwayat_penyakit' => 'Diabetes Gestasional', 'riwayat_alergi' => 'Sapi', 'kehamilan_ke' => 3, 'anak_hidup' => 2, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Rahmah', 'email' => 'rahmah@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567811'], 'profil' => ['tanggal_lahir' => '1998-08-08', 'usia' => 27, 'hpht' => '2025-02-28', 'hpl' => '2025-12-05', 'golongan_darah' => 'A', 'rhesus' => '+', 'berat_sebelum' => 54.0, 'tinggi_badan' => 163.0, 'alamat' => 'Jl. Durian No. 4, Jakarta Selatan', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Siti Rohmah', 'email' => 'siti.rohmah@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567812'], 'profil' => ['tanggal_lahir' => '1996-04-25', 'usia' => 29, 'hpht' => '2025-01-20', 'hpl' => '2025-10-27', 'golongan_darah' => 'B', 'rhesus' => '-', 'berat_sebelum' => 58.0, 'tinggi_badan' => 160.0, 'alamat' => 'Jl. Mente No. 19, Depok', 'riwayat_penyakit' => 'Asma', 'riwayat_alergi' => 'Pemanis', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Laily Nurjanah', 'email' => 'laily.nurjanah@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567813'], 'profil' => ['tanggal_lahir' => '1997-10-12', 'usia' => 28, 'hpht' => '2025-03-01', 'hpl' => '2025-12-06', 'golongan_darah' => 'AB', 'rhesus' => '+', 'berat_sebelum' => 56.0, 'tinggi_badan' => 165.0, 'alamat' => 'Jl. Jengkol No. 2, Tangerang', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Mariam', 'email' => 'mariam@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567814'], 'profil' => ['tanggal_lahir' => '1992-07-30', 'usia' => 33, 'hpht' => '2024-11-20', 'hpl' => '2025-08-27', 'golongan_darah' => 'O', 'rhesus' => '+', 'berat_sebelum' => 67.0, 'tinggi_badan' => 155.0, 'alamat' => 'Jl. Petai No. 21, Bogor', 'riwayat_penyakit' => 'Hipertensi Kronis', 'riwayat_alergi' => 'Obat keras', 'kehamilan_ke' => 4, 'anak_hidup' => 3, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Ulfa Azizah', 'email' => 'ulfa.azizah@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567815'], 'profil' => ['tanggal_lahir' => '2000-01-18', 'usia' => 26, 'hpht' => '2025-02-10', 'hpl' => '2025-11-17', 'golongan_darah' => 'A', 'rhesus' => '+', 'berat_sebelum' => 52.0, 'tinggi_badan' => 162.0, 'alamat' => 'Jl. Kakao No. 6, Bandung', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Diah Ayu', 'email' => 'diah.ayu@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567816'], 'profil' => ['tanggal_lahir' => '1995-09-05', 'usia' => 30, 'hpht' => '2025-01-15', 'hpl' => '2025-10-22', 'golongan_darah' => 'B', 'rhesus' => '+', 'berat_sebelum' => 60.0, 'tinggi_badan' => 158.0, 'alamat' => 'Jl. Vanili No. 10, Jakarta Pusat', 'riwayat_penyakit' => 'Anemia', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Siti Sarah', 'email' => 'siti.sarah@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567817'], 'profil' => ['tanggal_lahir' => '1999-03-22', 'usia' => 26, 'hpht' => '2025-03-08', 'hpl' => '2025-12-13', 'golongan_darah' => 'AB', 'rhesus' => '-', 'berat_sebelum' => 50.0, 'tinggi_badan' => 164.0, 'alamat' => 'Jl. Kayu Manis No. 3, Bekasi', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Erni Kurniasih', 'email' => 'erni.kurniasih@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567818'], 'profil' => ['tanggal_lahir' => '1994-11-14', 'usia' => 31, 'hpht' => '2024-12-25', 'hpl' => '2025-10-01', 'golongan_darah' => 'O', 'rhesus' => '+', 'berat_sebelum' => 65.0, 'tinggi_badan' => 156.0, 'alamat' => 'Jl. Cengkeh No. 15, Surabaya', 'riwayat_penyakit' => 'Thyroid', 'riwayat_alergi' => 'Seafood', 'kehamilan_ke' => 3, 'anak_hidup' => 2, 'keguguran' => 1]],
            ['user' => ['nama_lengkap' => 'Wahyuni', 'email' => 'wahyuni@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567819'], 'profil' => ['tanggal_lahir' => '1997-06-28', 'usia' => 28, 'hpht' => '2025-02-20', 'hpl' => '2025-11-27', 'golongan_darah' => 'A', 'rhesus' => '+', 'berat_sebelum' => 55.0, 'tinggi_badan' => 161.0, 'alamat' => 'Jl. Pala No. 9, Jakarta Barat', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Siti Nurhaliza', 'email' => 'siti.nurhaliza@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567820'], 'profil' => ['tanggal_lahir' => '1996-08-15', 'usia' => 29, 'hpht' => '2025-01-30', 'hpl' => '2025-11-06', 'golongan_darah' => 'B', 'rhesus' => '+', 'berat_sebelum' => 59.0, 'tinggi_badan' => 160.0, 'alamat' => 'Jl. Kemiri No. 7, Depok', 'riwayat_penyakit' => 'Asma', 'riwayat_alergi' => 'Kutu', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Nurul Azizah', 'email' => 'nurul.azizah@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567821'], 'profil' => ['tanggal_lahir' => '1998-12-10', 'usia' => 27, 'hpht' => '2025-03-12', 'hpl' => '2025-12-17', 'golongan_darah' => 'AB', 'rhesus' => '+', 'berat_sebelum' => 53.0, 'tinggi_badan' => 163.0, 'alamat' => 'Jl. Biji No. 11, Tangerang', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Evi Susilowati', 'email' => 'evi.susilowati@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567822'], 'profil' => ['tanggal_lahir' => '1993-05-20', 'usia' => 32, 'hpht' => '2024-11-30', 'hpl' => '2025-09-06', 'golongan_darah' => 'O', 'rhesus' => '-', 'berat_sebelum' => 64.0, 'tinggi_badan' => 157.0, 'alamat' => 'Jl. Daun No. 18, Bogor', 'riwayat_penyakit' => 'Jantung', 'riwayat_alergi' => 'Obat', 'kehamilan_ke' => 3, 'anak_hidup' => 2, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Rina Hartati', 'email' => 'rina.hartati@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567823'], 'profil' => ['tanggal_lahir' => '1999-09-08', 'usia' => 26, 'hpht' => '2025-02-05', 'hpl' => '2025-11-12', 'golongan_darah' => 'A', 'rhesus' => '+', 'berat_sebelum' => 51.0, 'tinggi_badan' => 162.0, 'alamat' => 'Jl. Batang No. 5, Bandung', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Nita Lestari', 'email' => 'nita.lestari@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567824'], 'profil' => ['tanggal_lahir' => '1995-02-14', 'usia' => 30, 'hpht' => '2025-01-25', 'hpl' => '2025-11-01', 'golongan_darah' => 'B', 'rhesus' => '+', 'berat_sebelum' => 58.0, 'tinggi_badan' => 159.0, 'alamat' => 'Jl. Ranting No. 14, Bekasi', 'riwayat_penyakit' => 'Anemia', 'riwayat_alergi' => 'Ikan', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Tri Wahyuni', 'email' => 'tri.wahyuni@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567825'], 'profil' => ['tanggal_lahir' => '1997-04-02', 'usia' => 28, 'hpht' => '2025-03-02', 'hpl' => '2025-12-07', 'golongan_darah' => 'AB', 'rhesus' => '+', 'berat_sebelum' => 56.0, 'tinggi_badan' => 165.0, 'alamat' => 'Jl. Akar No. 8, Jakarta Utara', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Sofia Rahmawati', 'email' => 'sofia.rahmawati@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567826'], 'profil' => ['tanggal_lahir' => '1994-10-28', 'usia' => 31, 'hpht' => '2024-12-15', 'hpl' => '2025-09-21', 'golongan_darah' => 'O', 'rhesus' => '+', 'berat_sebelum' => 63.0, 'tinggi_badan' => 156.0, 'alamat' => 'Jl. Umbi No. 16, Surabaya', 'riwayat_penyakit' => 'Diabetes Gestasional', 'riwayat_alergi' => 'Gula', 'kehamilan_ke' => 3, 'anak_hidup' => 2, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Dewi Khomariah', 'email' => 'dewi.khomariah@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567827'], 'profil' => ['tanggal_lahir' => '2000-06-12', 'usia' => 25, 'hpht' => '2025-02-28', 'hpl' => '2025-12-05', 'golongan_darah' => 'A', 'rhesus' => '-', 'berat_sebelum' => 49.0, 'tinggi_badan' => 164.0, 'alamat' => 'Jl. Wortel No. 2, Depok', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Heni Pujiastuti', 'email' => 'heni.pujiastuti@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567828'], 'profil' => ['tanggal_lahir' => '1996-01-05', 'usia' => 29, 'hpht' => '2025-01-20', 'hpl' => '2025-10-27', 'golongan_darah' => 'B', 'rhesus' => '+', 'berat_sebelum' => 57.0, 'tinggi_badan' => 161.0, 'alamat' => 'Jl. Kentang No. 12, Tangerang', 'riwayat_penyakit' => 'Thyroid', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Umi Kulsum', 'email' => 'umi.kulsum@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567829'], 'profil' => ['tanggal_lahir' => '1993-07-18', 'usia' => 32, 'hpht' => '2024-11-25', 'hpl' => '2025-09-01', 'golongan_darah' => 'AB', 'rhesus' => '+', 'berat_sebelum' => 66.0, 'tinggi_badan' => 155.0, 'alamat' => 'Jl. Bawang No. 20, Bogor', 'riwayat_penyakit' => 'Hipertensi', 'riwayat_alergi' => 'Sodium', 'kehamilan_ke' => 4, 'anak_hidup' => 3, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Rosi Nurul Hida', 'email' => 'rosi.nurul.hida@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567830'], 'profil' => ['tanggal_lahir' => '1998-03-25', 'usia' => 27, 'hpht' => '2025-02-15', 'hpl' => '2025-11-22', 'golongan_darah' => 'O', 'rhesus' => '+', 'berat_sebelum' => 54.0, 'tinggi_badan' => 163.0, 'alamat' => 'Jl. Cabai No. 6, Jakarta Timur', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Lina Marlina', 'email' => 'lina.marlina@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567831'], 'profil' => ['tanggal_lahir' => '1995-11-08', 'usia' => 30, 'hpht' => '2025-01-10', 'hpl' => '2025-10-17', 'golongan_darah' => 'A', 'rhesus' => '-', 'berat_sebelum' => 60.0, 'tinggi_badan' => 158.0, 'alamat' => 'Jl. Tomat No. 9, Bandung', 'riwayat_penyakit' => 'Asma', 'riwayat_alergi' => 'Panas', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Ika Wahyuni', 'email' => 'ika.wahyuni@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567832'], 'profil' => ['tanggal_lahir' => '1999-08-20', 'usia' => 26, 'hpht' => '2025-03-05', 'hpl' => '2025-12-10', 'golongan_darah' => 'B', 'rhesus' => '+', 'berat_sebelum' => 52.0, 'tinggi_badan' => 162.0, 'alamat' => 'Jl. Terong No. 4, Bekasi', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Vina Amelia', 'email' => 'vina.amelia@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567833'], 'profil' => ['tanggal_lahir' => '1994-05-15', 'usia' => 31, 'hpht' => '2024-12-20', 'hpl' => '2025-09-26', 'golongan_darah' => 'AB', 'rhesus' => '+', 'berat_sebelum' => 64.0, 'tinggi_badan' => 157.0, 'alamat' => 'Jl. Oyong No. 17, Surabaya', 'riwayat_penyakit' => 'Jantung', 'riwayat_alergi' => 'Obat', 'kehamilan_ke' => 3, 'anak_hidup' => 2, 'keguguran' => 1]],
            ['user' => ['nama_lengkap' => 'Ranti', 'email' => 'ranti@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567834'], 'profil' => ['tanggal_lahir' => '1997-12-22', 'usia' => 28, 'hpht' => '2025-02-25', 'hpl' => '2025-12-02', 'golongan_darah' => 'O', 'rhesus' => '+', 'berat_sebelum' => 55.0, 'tinggi_badan' => 160.0, 'alamat' => 'Jl. Labu No. 3, Jakarta Selatan', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Windi Astuti', 'email' => 'windi.astuti@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567835'], 'profil' => ['tanggal_lahir' => '1996-09-30', 'usia' => 29, 'hpht' => '2025-01-15', 'hpl' => '2025-10-22', 'golongan_darah' => 'A', 'rhesus' => '+', 'berat_sebelum' => 58.0, 'tinggi_badan' => 164.0, 'alamat' => 'Jl. Kacang No. 11, Depok', 'riwayat_penyakit' => 'Anemia', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Lilis Rohaeni', 'email' => 'lilis.rohaeni@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567836'], 'profil' => ['tanggal_lahir' => '1992-04-10', 'usia' => 33, 'hpht' => '2024-11-10', 'hpl' => '2025-08-17', 'golongan_darah' => 'B', 'rhesus' => '-', 'berat_sebelum' => 68.0, 'tinggi_badan' => 154.0, 'alamat' => 'Jl. Toge No. 19, Bogor', 'riwayat_penyakit' => 'Diabetes Kronis', 'riwayat_alergi' => 'Obat keras', 'kehamilan_ke' => 4, 'anak_hidup' => 3, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Sari Melati', 'email' => 'sari.melati@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567837'], 'profil' => ['tanggal_lahir' => '1999-02-08', 'usia' => 26, 'hpht' => '2025-03-01', 'hpl' => '2025-12-06', 'golongan_darah' => 'AB', 'rhesus' => '+', 'berat_sebelum' => 50.0, 'tinggi_badan' => 163.0, 'alamat' => 'Jl. Kembang No. 7, Tangerang', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Nurmi', 'email' => 'nurmi@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567838'], 'profil' => ['tanggal_lahir' => '1995-07-25', 'usia' => 30, 'hpht' => '2025-01-30', 'hpl' => '2025-11-06', 'golongan_darah' => 'O', 'rhesus' => '+', 'berat_sebelum' => 59.0, 'tinggi_badan' => 159.0, 'alamat' => 'Jl. Pucuk No. 13, Jakarta Barat', 'riwayat_penyakit' => 'Thyroid', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Fenti Novitasari', 'email' => 'fenti.novitasari@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567839'], 'profil' => ['tanggal_lahir' => '1998-10-15', 'usia' => 27, 'hpht' => '2025-02-20', 'hpl' => '2025-11-27', 'golongan_darah' => 'A', 'rhesus' => '+', 'berat_sebelum' => 53.0, 'tinggi_badan' => 161.0, 'alamat' => 'Jl. Teh No. 5, Bandung', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Titik Sumarni', 'email' => 'titik.sumarni@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567840'], 'profil' => ['tanggal_lahir' => '1994-01-20', 'usia' => 31, 'hpht' => '2024-12-05', 'hpl' => '2025-09-12', 'golongan_darah' => 'B', 'rhesus' => '+', 'berat_sebelum' => 65.0, 'tinggi_badan' => 156.0, 'alamat' => 'Jl. Kopi No. 21, Bekasi', 'riwayat_penyakit' => 'Hipertensi', 'riwayat_alergi' => 'Kafein', 'kehamilan_ke' => 3, 'anak_hidup' => 2, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Reni Agustin', 'email' => 'reni.agustin@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567841'], 'profil' => ['tanggal_lahir' => '1997-05-05', 'usia' => 28, 'hpht' => '2025-02-28', 'hpl' => '2025-12-05', 'golongan_darah' => 'AB', 'rhesus' => '-', 'berat_sebelum' => 56.0, 'tinggi_badan' => 165.0, 'alamat' => 'Jl. Kakao No. 8, Surabaya', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Desi Ratnasari', 'email' => 'desi.ratnasari@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567842'], 'profil' => ['tanggal_lahir' => '1996-11-12', 'usia' => 29, 'hpht' => '2025-01-25', 'hpl' => '2025-11-01', 'golongan_darah' => 'O', 'rhesus' => '+', 'berat_sebelum' => 60.0, 'tinggi_badan' => 160.0, 'alamat' => 'Jl. Gula No. 14, Jakarta Utara', 'riwayat_penyakit' => 'Anemia', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Eka Wahyuni', 'email' => 'eka.wahyuni@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567843'], 'profil' => ['tanggal_lahir' => '1999-06-28', 'usia' => 26, 'hpht' => '2025-03-10', 'hpl' => '2025-12-15', 'golongan_darah' => 'A', 'rhesus' => '+', 'berat_sebelum' => 51.0, 'tinggi_badan' => 162.0, 'alamat' => 'Jl. Garam No. 3, Depok', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Yanti', 'email' => 'yanti@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567844'], 'profil' => ['tanggal_lahir' => '1993-09-15', 'usia' => 32, 'hpht' => '2024-11-20', 'hpl' => '2025-08-27', 'golongan_darah' => 'B', 'rhesus' => '+', 'berat_sebelum' => 67.0, 'tinggi_badan' => 155.0, 'alamat' => 'Jl. Madu No. 18, Bogor', 'riwayat_penyakit' => 'Thyroid', 'riwayat_alergi' => 'Propolis', 'kehamilan_ke' => 4, 'anak_hidup' => 3, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Susi Susanti', 'email' => 'susi.susanti@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567845'], 'profil' => ['tanggal_lahir' => '1998-02-02', 'usia' => 27, 'hpht' => '2025-02-15', 'hpl' => '2025-11-22', 'golongan_darah' => 'AB', 'rhesus' => '+', 'berat_sebelum' => 54.0, 'tinggi_badan' => 164.0, 'alamat' => 'Jl. Royal No. 6, Tangerang', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Diana', 'email' => 'diana@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567846'], 'profil' => ['tanggal_lahir' => '1995-08-18', 'usia' => 30, 'hpht' => '2025-01-20', 'hpl' => '2025-10-27', 'golongan_darah' => 'O', 'rhesus' => '-', 'berat_sebelum' => 61.0, 'tinggi_badan' => 159.0, 'alamat' => 'Jl. Butter No. 10, Jakarta Selatan', 'riwayat_penyakit' => 'Asma', 'riwayat_alergi' => 'Laktosa', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Fransisca', 'email' => 'fransisca@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567847'], 'profil' => ['tanggal_lahir' => '2000-04-10', 'usia' => 25, 'hpht' => '2025-03-05', 'hpl' => '2025-12-10', 'golongan_darah' => 'A', 'rhesus' => '+', 'berat_sebelum' => 48.0, 'tinggi_badan' => 166.0, 'alamat' => 'Jl. Keju No. 2, Bandung', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Yuniarti', 'email' => 'yuniarti@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567848'], 'profil' => ['tanggal_lahir' => '1994-12-25', 'usia' => 31, 'hpht' => '2024-12-10', 'hpl' => '2025-09-16', 'golongan_darah' => 'B', 'rhesus' => '+', 'berat_sebelum' => 63.0, 'tinggi_badan' => 157.0, 'alamat' => 'Jl. Yoghurt No. 16, Bekasi', 'riwayat_penyakit' => 'Diabetes Gestasional', 'riwayat_alergi' => 'Susu sapi', 'kehamilan_ke' => 3, 'anak_hidup' => 2, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Venty', 'email' => 'venty@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567849'], 'profil' => ['tanggal_lahir' => '1997-10-30', 'usia' => 28, 'hpht' => '2025-02-28', 'hpl' => '2025-12-05', 'golongan_darah' => 'AB', 'rhesus' => '+', 'berat_sebelum' => 55.0, 'tinggi_badan' => 163.0, 'alamat' => 'Jl. Susu No. 9, Surabaya', 'riwayat_penyakit' => 'Tidak ada', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 1, 'anak_hidup' => 0, 'keguguran' => 0]],
            ['user' => ['nama_lengkap' => 'Sri Wahyuni', 'email' => 'sri.wahyuni@sikembang.com', 'password' => Hash::make('password'), 'role' => 'ibu_hamil', 'no_hp' => '081234567850'], 'profil' => ['tanggal_lahir' => '1996-03-12', 'usia' => 29, 'hpht' => '2025-01-15', 'hpl' => '2025-10-22', 'golongan_darah' => 'O', 'rhesus' => '+', 'berat_sebelum' => 58.0, 'tinggi_badan' => 160.0, 'alamat' => 'Jl. Es Krim No. 12, Jakarta Pusat', 'riwayat_penyakit' => 'Anemia', 'riwayat_alergi' => 'Tidak ada', 'kehamilan_ke' => 2, 'anak_hidup' => 1, 'keguguran' => 0]],
        ];

        foreach ($ibuHamilData as $data) {
            $user = User::create($data['user']);
            $user->profilIbuHamil()->create($data['profil']);
        }
    }
}
